### ISSUE TITLE
bağlantı için

### ISSUE THREAD

**Issue by serhatunur** [kivancagaogluu/gittigidiyor#2]
$config = [
    'apiKey' => 'xx',
    'secretKey' => 'xx',
    'nick' => 'xx',
    'password' => 'xx',
    'auth_user' => 'xx',
    'auth_pass' => 'xx',
    'lang' => 'tr',
];
gittigidiyor apiKey, secretKey  ,auth_user, auth_pass  bunları veriyor ama nick ve password olarak ne girmemiz gerekiyor yardımcı olurmusnuz

**Comment by kivancagaogluu** [comment]
Gittigidiyora kayıt olurken kullandığınız kullanıcı adı ve şifreniz

**Comment by serhatunur** [comment]
use bluntk\Gittigidiyor;

require_once __DIR__ . '/vendor/autoload.php';

$config = [
    'apiKey' => 'xx',
    'secretKey' => 'xx',
    'nick' => 'xx',
    'password' => 'xx',
    'auth_user' => 'xx',
    'auth_pass' => 'xx',
    'lang' => 'tr',
];
hocam verdiğiniz dosyaların içinde  bluntk klasörü yok gittigidiyor ile bağlantı kuramıyorum dosya yok hatası alıyorum

**Comment by kivancagaogluu** [comment]
Paketi vendor ile kurmanız gerekiyor

**Comment by serhatunur** [comment]
COMPOSER ile kurulumda hata veriyor

**Comment by serhatunur** [comment]
require kirvancagaogluu/gittigidiyor

**Comment by serhatunur** [comment]
[InvalidArgumentException]
  Could not find a matching version of package kirvancagaogluu/gittigidiyor. Check the package spelling, your version
   constraint and that the package is available in a stability which matches your minimum-stability (stable).
composer kurulumunda bu hatayı veriyor

**Comment by serhatunur** [comment]
composer require kivancagaogluu/gittigidiyor 
bu hatayı veriyor

  [InvalidArgumentException]
  Could not find a matching version of package kivancagaogluu/gittigidiyor. Check the package spelling, your version
  constraint and that the package is available in a stability which matches your minimum-stability (stable).

**Comment by kivancagaogluu** [comment]
``composer require bluntk/gittigidiyor``
 bu komutu çalıştırarak kurabilirisiniz

**Comment by serhatunur** [comment]
teşekkürler hocam eline sağlık bir sorum daha olucak
servisleri çağırmak için bir örnek yazarmısınız  bu şekilde ve birkaç tane daha denedim ulaşamadım 
$CategoryService =$gittigidiyor->Category->getCategories();

**Comment by serhatunur** [comment]
$statement = $pdo->prepare("SELECT * FROM pazaryeriapi");
$statement->execute();
$result = $statement->fetchAll(PDO::FETCH_ASSOC);							
foreach ($result as $row) {
	if($row['id'] == '3') {
		$GGsetApiKey    = $row['GapiKey'];
		$GGsetsecretKey = $row['GsecretKey'];
		$GGsetnick      = $row['Gnick'];
		$GGsetpassword  = $row['Gpassword'];
		$GGsetauth_user = $row['Gauth_user'];
		$GGsetauth_pass = $row['Gauth_pass'];
	}
}
use bluntk\Gittigidiyor;


$config = [
    'apiKey' => $GGsetApiKey,
    'secretKey' => $GGsetsecretKey,
    'nick' => $GGsetnick,
    'password' => $GGsetpassword,
    'auth_user' => $GGsetauth_user,
    'auth_pass' => $GGsetauth_pass,
    'lang' => 'tr',
];
$gittigidiyor = new Gittigidiyor($config);
$CategoryService =$gittigidiyor->Category->getCategories();
bağlantıyı sağlıyorum fakat fonksiyonları doğru cağıramıyorum

**Comment by serhatunur** [comment]
teşekkürler buldum

**Comment by kivancagaogluu** [comment]
Uygun bir vakitte dökümantasyon hazırlayacağım.

**Comment by serhatunur** [comment]
public function getCategorySpecs($params = [])
    {
        $defaults = ['categoryCode' => 'aa'];
        $parameters = array_merge($defaults, $params);
        $parameters['lang'] = $this->lang;
        $requestUrl = 'https://dev.gittigidiyor.com:8443/listingapi/ws/CategoryService?wsdl';
        $service = 'getCategorySpecs';
        $response = $this->request($requestUrl, $service, $parameters);
        return $response;
    }
hocam zamanını alıyorum ama bir sorum olucak kategorileri ve özelliklerini çekmek istediğim zaman sizin defaults a verdiğiniz kategorinin özelliklerini be ya kategorileri getiriyor biz eşleştirme yapmak için kategorileri ve özelliklerini çekmemiz gerekiyor ama defaults ayarları geçemiyorum nasıl yapmamız lazım
$params = [] kısmına nasıl bir değer vermemiz lazım

**Comment by serhatunur** [comment]
ürünleri açmak için kategori eşleştrimesi yapmam lazım tüm kategorileri çekmek istediğimiz zaman 100 ile sınırlı olduğu için çekemiyorum yanlış bir yol mu izliyorum

**Comment by serhatunur** [comment]
public function getCategorySpecs($params = [])
{
    $defaults = ['categoryCode' => 'aa'];
    $parameters = array_merge($defaults, $params);
    $parameters['lang'] = $this->lang;
    $requestUrl = 'https://dev.gittigidiyor.com:8443/listingapi/ws/CategoryService?wsdl';
    $service = 'getCategorySpecs';
    $response = $this->request($requestUrl, $service, $parameters);
    return $response;
}
fonksiyonu su sekilde düzeltmem mi lazım 

public function getCategorySpecs($params = [])
{
    $defaults = ['categoryCode' =>$params];
    $parameters = array_merge($defaults);
    $parameters['lang'] = $this->lang;
    $requestUrl = 'https://dev.gittigidiyor.com:8443/listingapi/ws/CategoryService?wsdl';
    $service = 'getCategorySpecs';
    $response = $this->request($requestUrl, $service, $parameters);
    return $response;
}
aa kısmına params ı verdım

**Comment by serhatunur** [comment]
public function getDeepestCategories($params = [])
    {
        $defaults = ['startOffSet' => 0, 'rowCount' => 100, 'withSpecs' => 0];
        $parameters = array_merge($defaults, $params);
        $parameters['lang'] = $this->lang;
        $requestUrl = 'https://dev.gittigidiyor.com:8443/listingapi/ws/CategoryService?wsdl';
        $service = 'getDeepestCategories';
        $response = $this->request($requestUrl, $service, $parameters);
        return $response;
    }
burdada aynı sekılde startOffSet' => 0 yerine startOffSet' => $params olarak yaparsam $params a verdiğimiz değer ile 100 100 saydırarak tüm kategorileri çekebilirim diye düşünüyorum

**Comment by kivancagaogluu** [comment]
readme dosyasına kategori servisi için iki adet örnek ekledim. Tüm servislerin mantığı oradakilerle aynı

**Comment by serhatunur** [comment]
teşekkürler hocam eline sağlık
