### ISSUE TITLE
Resim Hatası

### ISSUE THREAD

**Issue by serhatunur** [kivancagaogluu/gittigidiyor#3]
stdClass Object ( [ackCode] => failure [responseTime] => 2021-09-15 15:44:07 [error] => stdClass Object ( [errorId] => 546 [errorCode] => [GG-API-ERROR_546] [message] => Model bilgisine ait foto için url ya da base64 girişi yapmalısınız. [viewMessage] => Model bilgisine ait geçersiz resim bilgisi girdiniz. ) ) stdClass Object ( [ackCode] => failure [responseTime] => 2021-09-15 15:44:08 [error] => stdClass Object ( [errorId] => 546 [errorCode] => [GG-API-ERROR_546] [message] => Model bilgisine ait foto için url ya da base64 girişi yapmalısınız. [viewMessage] => Model bilgisine ait geçersiz resim bilgisi girdiniz. ) )

S.a Hocam ürün acarken yukardaki hatayı alıyorum Nerde hata yapıorum bulamadım Yardımcı olurmusun

<?php require_once('header.php'); ?>
<?php include "../vendor/autoload.php"; ?>
<?php
$statement = $pdo->prepare("SELECT * FROM pazaryeriapi");
$statement->execute();
$result = $statement->fetchAll(PDO::FETCH_ASSOC);							
foreach ($result as $row) {
	if($row['id'] == '3') {
		$GGsetApiKey    = $row['GapiKey'];
		$GGsetsecretKey = $row['GsecretKey'];
		$GGsetnick      = $row['Gnick'];
		$GGsetpassword  = $row['Gpassword'];
		$GGsetauth_user = $row['Gauth_user'];
		$GGsetauth_pass = $row['Gauth_pass'];
	}
}
use bluntk\Gittigidiyor;

$config = [
    'apiKey' => $GGsetApiKey,
    'secretKey' => $GGsetsecretKey,
    'nick' => $GGsetnick,
    'password' => $GGsetpassword,
    'auth_user' => $GGsetauth_user,
    'auth_pass' => $GGsetauth_pass,
    'lang' => 'tr',
];
$gittigidiyor = new Gittigidiyor($config);
		$statement = $pdo->prepare("SELECT * FROM tbl_product ");
		$statement->execute();
		$result = $statement->fetchAll(PDO::FETCH_ASSOC);	
		foreach ($result as $row) {
			
			$Barcode = $row['barcode'];
			$title = $row['p_name'];
			$subtitle = $row['altbaslik'];
			$Attributes1 = $row['ggatribusname1'];
			$Attributesvalue1 = $row['ggatribusdeger1'];
			$Attributes2 = $row['ggatribusname2'];
			$Attributesvalue2 = $row['ggatribusdeger2'];
			$Attributes3 = $row['ggatribusname3'];
			$Attributesvalue3 = $row['ggatribusdeger3'];
			$Attributes4 = $row['ggatribusname4'];
			$Attributesvalue4 = $row['ggatribusdeger4'];
			$Attributes5 = $row['ggatribusname5'];
			$Attributesvalue5 = $row['ggatribusdeger5'];
			$productMainId = $row['Product_code'];
			$description = $row['p_description'];
			$salePrice = $row['ggfiyati'];
			$categoryId = $row['ggcategoryCode'];
			$ggsure  = $row['ggsure'];
			$ggsehir  = $row['ggsehir'];
			$ggkargoalni  = $row['ggkargoalni'];
			$ggkargosablonu  = $row['ggkargoucreti'];
			$quantity = $row['p_qty'];
			$stockCode = $row['Product_code'];
			$dimensionalWeight = $row['desi'];
			$currencyType = $row['CurrencyType'];
			$listPrice = $row['p_old_price'];
			$brand = $row['Brand'];
			$images = 'http://kervansanal.com/xml/photo/000050109010.jpg';
			
$params = [];

$params['product'] = [
    'categoryCode' => $categoryId,
    'storeCategoryId' => '',
    'title' => $title,
    'subtitle' => $subtitle,
    'specs' => [
        'spec' => [
            [
                'name' => $Attributes1,
                'value' => $Attributesvalue1,
                'type' => 'Combo',
                'required' => true
            ],
            [
                'name' => $Attributes2,
                'value' => $Attributesvalue2,
                'type' => 'Combo',
                'required' => true
            ],
            [
                'name' => $Attributes3,
                'value' => $Attributesvalue3,
                'type' => 'Combo',
                'required' => true
            ],
			            [
                'name' => $Attributes4,
                'value' => $Attributesvalue4,
                'type' => 'Combo',
                'required' => true
            ],
            [
                'name' => $Attributes5,
                'value' => $Attributesvalue5,
                'type' => 'Combo',
                'required' => true
            ],

        ]
    ],
    'photos' => [
        'photo' => [
            [
                'photoId' => 0,
                'url' => $images,
                'base64' => ''
            ],
            [
                'photoId' => 1,
                'url' => '',
                'base64' => ''
            ],
            [
                'photoId' => 2,
                'url' => '',
                'base64' => ''
            ],
        ]
    ],
    'pageTemplate' => 1,
    'description' => $description,
    'startDate' => '',
    'catalogId' => '',
    'catalogDetail' => '',
    'catalogFilter' => '',
    'format' => 'S',
    'startPrice' => '',
    'buyNowPrice' => $salePrice,
    'listingDays' => $ggsure,
    'productCount' => 1,
    'cargoDetail' => [
        'city' => $ggsehir,
        'shippingPayment' => $ggkargosablonu,
        'shippingWhere' => $ggkargoalni,
        'cargoCompanyDetails' => [
            'cargoCompanyDetail' => [
                'name' => 'aras',
                'cityPrice' => 10.00,
                'countryPrice' => 10.00,
            ]
        ],
        'shippingTime' => [
            'days' => 'today',
            'beforeTime' => '10:30'
        ],
    ],
    'affiliateOption' => false,
    'boldOption' => false,
    'catalogOption' => false,
    'vitrineOption' => false,
    'globalTradeItemNo' => null,
    'manufacturerPartNo' => '',
    'variantGroups' => [
        'variantGroup' => [
            [
                'variants' => [
                    'variant' => [
                        [
                            'variantSpecs' => [
                                'variantSpec' => [
                                    [
                                        'nameId' => '',
                                        'valueId' => '',
                                    ],
                                    [
                                        'nameId' => '',
                                        'valueId' => '',
                                    ],
                                ]
                            ],
                            'quantity' => $quantity,
                            'stockCode' => $stockCode,
                        ],
                        [
                            'variantSpecs' => [
                                'variantSpec' => [
                                    [
                                        'nameId' => '',
                                        'valueId' => '',
                                    ],
                                    [
                                        'nameId' => '',
                                        'valueId' => '',
                                    ],
                                ]
                            ],
                            'quantity' => $quantity,
                            'stockCode' => $stockCode,
                        ],
                    ]
                ],
                'photos' => [
                    'photo' => [
                        [
                            'photoId' => 0,
                            'url' => ''
                        ]
                    ]
                ],

            ]

        ]
    ]
];

$productService = $gittigidiyor->product();

$result = $productService->insertAndActivateProduct($params);
print_r($result);
		}

?>
<?php require_once('footer.php'); ?>

**Comment by kivancagaogluu** [comment]
Bu gibi sorunları gittigidiyorun api destek mailine yazmanız daha doğru olur zira kodlarda herhangi bir sorun yok.
